language: java
jdk:
- oraclejdk8
script: mvn clean install
deploy:
  provider: heroku
  api_key:
    secure: T1/Jlu0SYxoBIplcW3gBSN0Z/v0KA5D2yeXoLt+rEPY3SzDkkVFHaZ7zN1FvHHpXU8bmXBLQYqohNi8rAZgaF2W0NzMAKKzGpq+4wpHWLZYHMCIYGJWMYlho7v5HzWYowP9J40rjEO4vFh7fAHbwpGSlC+6gWfcxkzJs4wyPNtZ+do+mMKtRmPpEYKbPgWnPumEoebKK6XibZPzq2mZ2li8WpC/II/UlmYmFdqE5Yo1LyqPqMfdc8xLF81zYZmJurWrZNJTcKJp0h6RIs9AXnMFneV+NfEnalQ9k2amwrpbfHMyuK6wphr8Jyxh4FR3M7TCGNuO12tViPKZRO9WCIg++KuZfcJg4kuPAcIwgk2eLCYvWbfZ8DmdZ0hlKZAnOA8ZAKlsOLTUvt/Nw13u1DOogdFT0bdV+umX9K0LUfgJ7t7BQn/T2w5xnaUDZQpWnctaA4prTa94yzs4kaqpJ5qxTWd9BoJ5CMe9DF3yH2VRcdwQzjGI/V4Sifpp9bJBvvShjq5WUOfwexgaLA/Uq1ZS2nPq8SJ2RYtu8L2ocGMxm5p35cyxGp4HJFqO1WNjM87Pd73FMDnwpoU4irWE0RmWoCC6LQRLOLgrhQr5WOTypBWqPc6V47S0z+VaYKE6AAfAKRzuQEuQ9Z2MIAaqep+55wxSWBx+AGVHjrUWqPJY=
  app: ayhan-springboot-template
  on:
    repo: ayhanugurlu/springboot-template
